### ISSUE TITLE
使用 npm run dev 启动报错 并且不能使用

### ISSUE THREAD

**Issue by xfk520** [Exrick/x-boot#28]
Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

**Comment by xfk520** [comment]
上面是报错信息

**Comment by xfk520** [comment]
error  in ./src/views/sys/menu-manage/menuManage.vue?vue&type=style&index=0&lang=less&

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

 @ ./node_modules/vue-style-loader??ref--10-oneOf-1-0!./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/sys/menu-manage/menuManage.vue?vue&type=style&index=0&lang=less& 4:14-477 14:3-18:5 15:22-485
 @ ./src/views/sys/menu-manage/menuManage.vue?vue&type=style&index=0&lang=less&
 @ ./src/views/sys/menu-manage/menuManage.vue
 @ ./src/views lazy ^\.\/.*\.vue$ namespace object
 @ ./src/libs/lazyLoading.js
 @ ./src/libs/util.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:34079/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by xfk520** [comment]
我的 邮箱是  x66128@qq.com  ，求大神救一下。

**Comment by Exrick** [comment]
@xfk520 更新package.json中依赖less-loader为最新版本，等待提交修复
``` javascript
"devDependencies": {
    "less": "^3.10.1",
    "less-loader": "^5.0.0"
  }
```

**Comment by xfk520** [comment]
谢谢

**Comment by xfk520** [comment]
作者啊！ 现在遇到一个问题！在 vue.config.js 中设置了 port 但是启动后端口还是随机的！请问这个问题怎么解决啊

**Comment by Exrick** [comment]
portfinder 1.0.23 修复了这个问题，请删除项目里的 package-lock.json 或者 yarn.lock 然后重新安装依赖 @xfk520
