### ISSUE TITLE
导入sql文件报错

### ISSUE THREAD

**Issue by crazybaozi** [Exrick/x-boot#30]
我用的是mysql5.7, 导入sql后报错: 
Specified key was too long; max key length is 767 bytes
===========================================
CREATE TABLE QRTZ_JOB_DETAILS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)  用varchar做索引性能不好吧, 而且还超长.
);

**Comment by Exrick** [comment]
这个是Quartz官方提供的sql表 你试试单独导入quartz.sql呢 5.7的不应该有问题
